"use client"
import "./globals.css"
import type { Metadata } from "next"
import { Provider } from "react-redux"
import { store } from "@/redux/store"

const metadata: Metadata = {
  title: "Finance App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  )
}
