import "./globals.css"
import type { Metadata } from "next"
import AppProvider from "@/redux/AppProvider"

export const metadata: Metadata = {
  title: "Finance App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
